#ifndef FACTORY_OF_THE_FUTURE_NETWORK_COMMANDS_H
#define FACTORY_OF_THE_FUTURE_NETWORK_COMMANDS_H

#define CMD_CLOSE_CONNECTION -1
#define CMD_INIT_NEW_FACTORY 0 // (IP) -> (ID)
#define CMD_ANNOUNCE_NEW_HOST 1  // (IP, ID) -> OK
//#define CMD_CONNECT_BACK_HOST 2  // (IP, ID) -> OK
#define CMD_SEND_SENSOR_DATA 3  // (ID, TEMPERATURE, HUMIDITY, PRESSURE) -> OK
#define CMD_TRIGGER_ALARM 4  // (ID) -> OK
#define CMD_INIT_ML 5 // (IP) -> (ID)

#endif //FACTORY_OF_THE_FUTURE_NETWORK_COMMANDS_H
